name: restaurant_app_dicoding
description: "A dicoding flutter submission project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.8.0+1
  flutter_colorpicker: ^1.1.0
  flutter_cache_manager: ^3.3.0
  shared_preferences: ^2.5.2
  sqflite: ^2.2.2
  path: ^1.8.0
  flutter_local_notifications: ^18.0.1
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  permission_handler: ^11.3.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  sqflite_common_ffi: ^2.3.4+4
  path_provider_platform_interface: ^2.1.2

dev_dependencies:
  test: ^1.25.2
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/PlusJakartaSans-Bold.ttf
    - assets/fonts/PlusJakartaSans-BoldItalic.ttf
    - assets/fonts/PlusJakartaSans-ExtraBold.ttf
    - assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
    - assets/fonts/PlusJakartaSans-Italic.ttf
    - assets/fonts/PlusJakartaSans-Light.ttf
    - assets/fonts/PlusJakartaSans-LightItalic.ttf
    - assets/fonts/PlusJakartaSans-Medium.ttf
    - assets/fonts/PlusJakartaSans-MediumItalic.ttf
    - assets/fonts/PlusJakartaSans-Regular.ttf
    - assets/fonts/PlusJakartaSans-SemiBold.ttf
    - assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
    - assets/images/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
